/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Begin a signing flow. Returns a CBOR `{handle, step}` Buffer (decode-only for the caller). */
export declare function beginSigning(document: Buffer, environment: string, cscApi: string, clientId: string, clientSecret: string, redirectUri: string, conformance: string, nowUnix: number, entropy: Buffer, tsaUrl?: string | undefined | null, optionsJson?: string | undefined | null): Buffer
/** Resume after a redirect return (OAuth `code` + `state`). Returns a CBOR `{handle, step}` Buffer. */
export declare function resumeRedirect(handle: Buffer, code: string, state: string, nowUnix: number, entropy: Buffer): Buffer
/** Resume after a redirect OAuth error (`error` + `state`). Returns a CBOR `{handle, step}` Buffer. */
export declare function resumeRedirectError(handle: Buffer, error: string, state: string, nowUnix: number, entropy: Buffer): Buffer
/** Resume after performing an HTTP effect (status + body). Returns a CBOR `{handle, step}` Buffer. */
export declare function resumeHttp(handle: Buffer, status: number, body: Buffer, nowUnix: number, entropy: Buffer): Buffer
